using FluentAssertions;
using Newtonsoft.Json.Linq;
using Server.DAL;
using Xunit;

namespace Server.Tests.Integration
{
    public class MainProviderTest
    {
        [Fact]
        public void SaveChanges_should_save_QnA_first_and_its_Maps_latter()
        {
            var ctxProvider = new TestProvider();
            var bundle = JObject.Parse(@"{
              ""entities"": [
                {
                  ""Id"": -2,
                  ""QnAId"": -1,
                  ""TagId"": 1,
                  ""entityAspect"": {
                    ""entityTypeName"": ""MapQAT:#Server.Models"",
                    ""defaultResourceName"": ""MapsQAT"",
                    ""entityState"": ""Added"",
                    ""originalValuesMap"": {},
                    ""autoGeneratedKey"": {
                      ""propertyName"": ""Id"",
                      ""autoGeneratedKeyType"": ""Identity""
                    }
                  }
                },
                {
                  ""Id"": -3,
                  ""QnAId"": -1,
                  ""TagId"": 2,
                  ""entityAspect"": {
                    ""entityTypeName"": ""MapQAT:#Server.Models"",
                    ""defaultResourceName"": ""MapsQAT"",
                    ""entityState"": ""Added"",
                    ""originalValuesMap"": {},
                    ""autoGeneratedKey"": {
                      ""propertyName"": ""Id"",
                      ""autoGeneratedKeyType"": ""Identity""
                    }
                  }
                },{
                  ""Id"": -1,
                  ""Question"": ""test"",
                  ""Answer"": ""sdfsdf"",
                  ""Order"": null,
                  ""entityAspect"": {
                    ""entityTypeName"": ""QnA:#Server.Models"",
                    ""defaultResourceName"": ""QnAs"",
                    ""entityState"": ""Added"",
                    ""autoGeneratedKey"": {
                      ""propertyName"": ""Id"",
                      ""autoGeneratedKeyType"": ""Identity""
                    }
                  }
                }
              ],
              ""saveOptions"": {}
            }");

            ctxProvider.SaveChanges(bundle);
        }
    }
}
